publisher:
  engineBaseJar:
    resourcePath: "/runtime/h2o-scoring-engine-base-0.5.4.jar"
    
tapApiService:
  url: ${API_SERVICE_HOST:localhost}
  oauth:
    accessTokenUri: ${API_SERVICE_TOKEN_URI:}
    clientId: ${API_SERVICE_CLIENT_ID:}
    clientSecret: ${API_SERVICE_CLIENT_SECRET:}
    
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.trustedanalytics.h2oscoringengine: DEBUG

    