publisher:
  engineBaseJar:
    resourcePath: "/runtime/h2o-scoring-engine-base-0.5.7.jar"
    
tapApiService:
  url: ${API_SERVICE_HOST:localhost}
  oauth:
    accessTokenUri: ${API_SERVICE_TOKEN_URI:}
    clientId: ${API_SERVICE_CLIENT_ID:}
    clientSecret: ${API_SERVICE_CLIENT_SECRET:}
    
modelCatalog:
  url: ${MODEL_CATALOG_URL:localhost}
  oauth:
    accessTokenUri: ${MODEL_CATALOG_TOKEN_URI:}
    clientId: ${MODEL_CATALOG_CLIENT_ID:}
    clientSecret: ${MODEL_CATALOG_CLIENT_SECRET:}
    
keyCounter:
  host: ${KEY_COUNTER_HOST:localhost}
  username: ${KEY_COUNTER_USER:}
  password: ${KEY_COUNTER_PASSWORD:}
    
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.trustedanalytics.h2oscoringengine: DEBUG

    